//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.BenimModelim
{
    using System;
    using System.Collections.Generic; 
    using System.ComponentModel; 
    using System.Runtime.CompilerServices; 
    using System.Collections.ObjectModel; 
    public partial class AnaStok: INotifyPropertyChanged
    {
    
    public event PropertyChangedEventHandler PropertyChanged;
 protected void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
{
var handler = PropertyChanged;
if (handler != null)
{
handler(this, new PropertyChangedEventArgs(propertyName));
}
}

    
    
        private int _Id; 
        public int Id
        {
            get { return _Id; } 
            set
            {
                if (value == _Id) return;
                _Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok1Id; 
        public int AraStok1Id
        {
            get { return _AraStok1Id; } 
            set
            {
                if (value == _AraStok1Id) return;
                _AraStok1Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok2Id; 
        public int AraStok2Id
        {
            get { return _AraStok2Id; } 
            set
            {
                if (value == _AraStok2Id) return;
                _AraStok2Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok3Id; 
        public int AraStok3Id
        {
            get { return _AraStok3Id; } 
            set
            {
                if (value == _AraStok3Id) return;
                _AraStok3Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok4Id; 
        public int AraStok4Id
        {
            get { return _AraStok4Id; } 
            set
            {
                if (value == _AraStok4Id) return;
                _AraStok4Id = value;
                NotifyPropertyChanged();
            }
        }
    
    
        public virtual AraStok1 AraStok1 { get; set; }
        public virtual AraStok2 AraStok2 { get; set; }
        public virtual AraStok3 AraStok3 { get; set; }
        public virtual AraStok4 AraStok4 { get; set; }
    }
}
