//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.BenimModelim
{
    using System;
    using System.Collections.Generic; 
    using System.ComponentModel; 
    using System.Runtime.CompilerServices; 
    using System.Collections.ObjectModel; 
    public partial class hat1: INotifyPropertyChanged
    {
    
    public event PropertyChangedEventHandler PropertyChanged;
 protected void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
{
var handler = PropertyChanged;
if (handler != null)
{
handler(this, new PropertyChangedEventArgs(propertyName));
}
}

    
    
        private int _Id; 
        public int Id
        {
            get { return _Id; } 
            set
            {
                if (value == _Id) return;
                _Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok1Id; 
        public int AraStok1Id
        {
            get { return _AraStok1Id; } 
            set
            {
                if (value == _AraStok1Id) return;
                _AraStok1Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _A; 
        public string A
        {
            get { return _A; } 
            set
            {
                if (value == _A) return;
                _A = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _B; 
        public string B
        {
            get { return _B; } 
            set
            {
                if (value == _B) return;
                _B = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _C; 
        public string C
        {
            get { return _C; } 
            set
            {
                if (value == _C) return;
                _C = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _D; 
        public string D
        {
            get { return _D; } 
            set
            {
                if (value == _D) return;
                _D = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _hiz1; 
        public string hiz1
        {
            get { return _hiz1; } 
            set
            {
                if (value == _hiz1) return;
                _hiz1 = value;
                NotifyPropertyChanged();
            }
        }
    
    
        public virtual AraStok1 AraStok1 { get; set; }
    }
}
