//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.BenimModelim
{
    using System;
    using System.Collections.Generic; 
    using System.ComponentModel; 
    using System.Runtime.CompilerServices; 
    using System.Collections.ObjectModel; 
    public partial class hat2: INotifyPropertyChanged
    {
    
    public event PropertyChangedEventHandler PropertyChanged;
 protected void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
{
var handler = PropertyChanged;
if (handler != null)
{
handler(this, new PropertyChangedEventArgs(propertyName));
}
}

    
    
        private int _Id; 
        public int Id
        {
            get { return _Id; } 
            set
            {
                if (value == _Id) return;
                _Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok2Id; 
        public int AraStok2Id
        {
            get { return _AraStok2Id; } 
            set
            {
                if (value == _AraStok2Id) return;
                _AraStok2Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _A; 
        public string A
        {
            get { return _A; } 
            set
            {
                if (value == _A) return;
                _A = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _B; 
        public string B
        {
            get { return _B; } 
            set
            {
                if (value == _B) return;
                _B = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _hiz2; 
        public string hiz2
        {
            get { return _hiz2; } 
            set
            {
                if (value == _hiz2) return;
                _hiz2 = value;
                NotifyPropertyChanged();
            }
        }
    
    
        public virtual AraStok2 AraStok2 { get; set; }
    }
}
