//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.BenimModelim
{
    using System;
    using System.Collections.Generic; 
    using System.ComponentModel; 
    using System.Runtime.CompilerServices; 
    using System.Collections.ObjectModel; 
    public partial class hat3: INotifyPropertyChanged
    {
    
    public event PropertyChangedEventHandler PropertyChanged;
 protected void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
{
var handler = PropertyChanged;
if (handler != null)
{
handler(this, new PropertyChangedEventArgs(propertyName));
}
}

    
    
        private int _Id; 
        public int Id
        {
            get { return _Id; } 
            set
            {
                if (value == _Id) return;
                _Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private int _AraStok3Id; 
        public int AraStok3Id
        {
            get { return _AraStok3Id; } 
            set
            {
                if (value == _AraStok3Id) return;
                _AraStok3Id = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _C; 
        public string C
        {
            get { return _C; } 
            set
            {
                if (value == _C) return;
                _C = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _D; 
        public string D
        {
            get { return _D; } 
            set
            {
                if (value == _D) return;
                _D = value;
                NotifyPropertyChanged();
            }
        }
    
        private string _hiz3; 
        public string hiz3
        {
            get { return _hiz3; } 
            set
            {
                if (value == _hiz3) return;
                _hiz3 = value;
                NotifyPropertyChanged();
            }
        }
    
    
        public virtual AraStok3 AraStok3 { get; set; }
    }
}
