//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.BenimModelim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnaStok> AnaStokSet { get; set; }
        public virtual DbSet<AraStok1> AraStok1Set { get; set; }
        public virtual DbSet<AraStok2> AraStok2Set { get; set; }
        public virtual DbSet<AraStok3> AraStok3Set { get; set; }
        public virtual DbSet<AraStok4> AraStok4Set { get; set; }
        public virtual DbSet<hat1> hat1Set { get; set; }
        public virtual DbSet<hat2> hat2Set { get; set; }
        public virtual DbSet<hat3> hat3Set { get; set; }
        public virtual DbSet<hat4> hat4Set { get; set; }
    }
}
